Fix string truncation warnings related to PATH_MAX
oetiker/rrdtool-1.x pull request #1244
Opened 2024-01-06 16:00 UTC by hramrach

There are a number of places where rrdtool combines multiple PATH_MAX sized strings into one.

PATH_MAX is a constant that tends to work in practice a lot of the time but may not reflect the real capabilities of the system in real time.

In place of on-stack buffers of PATH_MAX size allocate memory dynamically. Initialize the pointers to NULL so they can be all freed unconditionally on exit.

Fixes: #1223

Note: this is not tested, and the changes are substantial. If this looks like a generally good way to do it it warrants running the code with valgrind or similar.

Also it is not clear that asprintf implementation is needed. configure tests for asprintf presence but a windows implementation is provided.

2024-01-06 18:07 UTC, c72578 commented
> Also it is not clear that asprintf implementation is needed. configure tests for asprintf presence but a windows implementation is provided.

Concerning Windows, MSYS2 MinGW-w64 provides `asprintf`:
`checking for asprintf... yes`

And for the MSVC builds (librrd-8.vcxproj) there are:
[win32/asprintf.c](https://github.com/oetiker/rrdtool-1.x/blob/master/win32/asprintf.c)
[win32/asprintf.h](https://github.com/oetiker/rrdtool-1.x/blob/master/win32/asprintf.h)

2024-01-07 07:54 UTC, oetiker commented
the build-test-linux does run valgrind ... not sure if the tests are hitting path areas ... maybe have a look?


this is how to run the tests on the commandline

```
        make check TESTS_STYLE="valgrind-logfile" TESTS="modify1 modify2 modify3 modify4 modify5 tune1 tune2 graph1 rrdcreate dump-restore create-with-source-1 create-with-source-2 create-with-source-3 create-with-source-4 create-with-source-and-mapping-1 create-from-template-1 dcounter1 vformatter1 list1 pdp-calc1"

```

2024-01-07 10:54 UTC, hramrach commented
And there is whole printf implementation so there should not be a problem with any platform lacking asprinf.

Yes, I see that the tests run valgrind, and the coverage tool points out that some of the error cases are not tested.

2024-01-08 09:03 UTC, oetiker approved these changes

2024-01-08 09:04 UTC, oetiker requested changes
please add to the CHANGES file!

2024-01-08 12:59 UTC, oetiker approved these changes

2024-01-08 12:59 UTC, merged