Return success for rrdcached pending on empty
oetiker/rrdtool-1.x pull request #809
Opened 2017-07-14 17:39 UTC by stevenh

If we have no pending entries for a file return success with no entries instead of returning an error.

2017-07-14 17:39 UTC, stevenh commented
This fixes #808

2017-07-20 12:26 UTC, oetiker requested changes

2017-07-20 12:26 UTC, oetiker commented on src/rrd_daemon.c
wouldn't it make more sense to just execute the following for loop only IF ci != NULL instead of duplicating the code above ?

2017-07-20 20:46 UTC, stevenh commented on src/rrd_daemon.c
Sure, also cleaned up the rest of the flow as well as the goto isn't needed

2017-07-20 21:46 UTC, oetiker requested changes

2017-07-20 21:46 UTC, oetiker commented on src/rrd_daemon.c
> +  return send_response(sock, RESP_OK, "updates pending\n");
hmmm still not quite sure if this is correct ... if no pending updates (ci == NULL) are found, then the message 'updates pending' seems odd ...

2017-07-21 02:11 UTC, stevenh commented on src/rrd_daemon.c
> +  return send_response(sock, RESP_OK, "updates pending\n");
The message will actually be:
```
0 updates pending
```
Which IMO makes perfect sense

2017-07-21 06:20 UTC, oetiker commented on src/rrd_daemon.c
> +  return send_response(sock, RESP_OK, "updates pending\n");
oh my bad ... :) send_response counts what has been added .. all well :) ok

2017-07-21 06:20 UTC, merged